"""Builds live_check_short.py from live_check.py: the short-question half only,
three attempts each, plus "hello". Kept as a script so the derivation is
reviewable rather than a one-off edit."""
import pathlib

HERE = pathlib.Path(__file__).parent
src = (HERE / "live_check.py").read_text()
src = src.replace('OUT = pathlib.Path(__file__).parent / "live_runs"', 'OUT = pathlib.Path(__file__).parent / "live_runs_short"')
src = src.replace(
    "    for question in ASK_BACK:\n        for attempt in (1, 2):",
    '    for question in ASK_BACK + ["hello"]:\n        for attempt in (1, 2, 3):',
)
start = src.index("    for question in BOTH_DEPTHS:")
end = src.index('    (OUT / "all.json")')
src = src[:start] + src[end:]
src = src.replace('print("wrote live_runs/all.json")', 'print("wrote live_runs_short/all.json")')
src = src.replace(
    '"""Items 12.3, 12.9, 12.10 and 12.16, measured together on the merged code.',
    '"""Item 12.3 re-measured after the ask-back classifier gained two principles\n'
    "(a bare name of a resource is still a subject; when unsure, ask back): every\n"
    'bare short question three times, plus "hello" and a short question that says\n'
    "what it wants. Generated by make_short_check.py from live_check.py.\n\n"
    "Items 12.3, 12.9, 12.10 and 12.16, measured together on the merged code.",
)
(HERE / "live_check_short.py").write_text(src)
print("ok")
