"""SQLAlchemy ORM models for the user-data schema.

Spec: Technical_specification.md Section 15 (lines 2361-2555), the six
tables `users`, `auth_sessions`, `sessions`, `interactions`, `cq_candidates`,
`saved_queries`, plus `guest_sessions` (build phase 4.10, T-4.10-02,
design decision 3, `tracker/phase_4.10.md`), a Section 15 extension not in
the original locked spec text.

Depends on:
    - system_03_search_agent.data.base (Base)

Reads:
    - Nothing at import time.

Writes:
    - Nothing at import time. Table creation is owned exclusively by the
      Alembic migration in alembic/versions/0001_user_data_schema.py, never
      by Base.metadata.create_all() in application code.

This module never imports, references, or constructs a connection to the
knowledge-graph database or its read-only role.

The `alembic/versions/0001_user_data_schema.py` migration is hand-written
directly from Section 15's SQL rather than autogenerated from these classes,
so it is the authoritative source for exact index definitions (index name,
column order direction, and opclass). The Index objects declared here mirror
the migration for ORM-level documentation and future autogenerate diffing;
where a plain SQLAlchemy Index cannot express a Postgres-specific detail
(the `created_at DESC` ordering), the ORM declaration is a same-column,
ascending best-effort mirror and the migration remains authoritative.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Any

from sqlalchemy import (
    ARRAY,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from system_03_search_agent.data.base import Base


class User(Base):
    """The `users` table: one row per registered account (Section 15)."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    profile: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    __table_args__ = (
        # F-1.1-08: the plain UNIQUE on `email` above is byte-exact, so
        # `USER@example.com` and `user@example.com` are two accounts. The
        # case-insensitive guarantee is this functional unique index on
        # `lower(email)`, added in alembic revision 0002, which holds even
        # for a code path that skips the schema-level normalization in
        # auth/schemas.py.
        Index("ux_users_email_lower", text("lower(email)"), unique=True),
    )


class AuthSession(Base):
    """The `auth_sessions` table: login state and refresh tokens (Section 15).

    Distinct from `ChatSession` below: this tracks login state, the chat
    session tracks a query workspace. Revoking a login must never erase a
    running conversation's context.
    """

    __tablename__ = "auth_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    refresh_token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # F-1.1-07: the ceiling a whole rotation chain may never outlive,
    # carried forward unchanged from the login that started the chain,
    # unlike `expires_at`, which every rotation renews. Nullable because
    # revision 0002 adds it to a table that already holds rows; a NULL
    # means a row written before that revision, and the router treats it
    # as capped at `created_at + the absolute TTL`.
    absolute_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(Text, nullable=True)
    ip_hash: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        # F-1.1-12: every auth call filters this column, and nothing
        # prevented two rows from sharing a hash. A unique index is both
        # halves of that finding at once, the uniqueness the code already
        # assumed and the index the lookups always needed.
        Index("ux_auth_sessions_refresh_token_hash", "refresh_token_hash", unique=True),
    )


class ChatSession(Base):
    """The `sessions` table: a chat or query workspace session (Section 15).

    Named ChatSession at the Python class level (the table name stays
    `sessions`) so this never collides with sqlalchemy.orm.Session.
    """

    __tablename__ = "sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_active_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    experiment_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    experiment_arm: Mapped[str | None] = mapped_column(Text, nullable=True)


class Interaction(Base):
    """The `interactions` table: the feedback-loop and memory substrate (Section 15)."""

    __tablename__ = "interactions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    trace_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    query_text: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_entities: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    query_class: Mapped[str] = mapped_column(Text, nullable=False)
    route: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    trust_signal: Mapped[str] = mapped_column(Text, nullable=False)
    rubric_outcome: Mapped[str] = mapped_column(Text, nullable=False)
    rubric_score: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    citations: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    coverage_tags: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default=text("'{}'::text[]")
    )
    user_feedback: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    experiment_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    experiment_arm: Mapped[str | None] = mapped_column(Text, nullable=True)
    cost_usd: Mapped[Any | None] = mapped_column(Numeric(9, 6), nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "query_class IN ('lookup','single_hop','multi_hop','aggregate','exploratory')",
            name="ck_interactions_query_class",
        ),
        CheckConstraint(
            "trust_signal IN ('answer','flag','ask','refuse')",
            name="ck_interactions_trust_signal",
        ),
        CheckConstraint(
            "rubric_outcome IN ('pass','fail','abstain')",
            name="ck_interactions_rubric_outcome",
        ),
        CheckConstraint(
            "rubric_score BETWEEN 0 AND 16",
            name="ck_interactions_rubric_score",
        ),
        Index("idx_interactions_created_at", "created_at"),
        Index("idx_interactions_user_id", "user_id"),
        Index("idx_interactions_rubric", "rubric_outcome"),
        Index("idx_interactions_coverage_tags", "coverage_tags", postgresql_using="gin"),
        Index(
            "idx_interactions_query_trgm",
            "query_text",
            postgresql_using="gin",
            postgresql_ops={"query_text": "gin_trgm_ops"},
        ),
    )


class CqCandidate(Base):
    """The `cq_candidates` table: proposed and promoted competency questions (Section 15)."""

    __tablename__ = "cq_candidates"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'proposed'")
    )
    representative_query: Mapped[str] = mapped_column(Text, nullable=False)
    source_interaction_ids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, server_default=text("'{}'::uuid[]")
    )
    frequency_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    wedge_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    moat_gate_provenance: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    moat_gate_deterministic: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    moat_rank: Mapped[str | None] = mapped_column(Text, nullable=True)
    llm_judge_rationale: Mapped[str | None] = mapped_column(Text, nullable=True)

    reviewed_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    review_decision: Mapped[str | None] = mapped_column(Text, nullable=True)
    review_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    few_shot_example: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    eval_case: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    promoted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "status IN ('proposed','approved','rejected','promoted','retired')",
            name="ck_cq_candidates_status",
        ),
        CheckConstraint(
            "wedge_type IN ('gene-variant-literature','pathogen-sequence-outbreak',"
            "'paper-data-tool','other')",
            name="ck_cq_candidates_wedge_type",
        ),
        CheckConstraint(
            "moat_rank IN ('tier_1','tier_2','none')",
            name="ck_cq_candidates_moat_rank",
        ),
        CheckConstraint(
            "review_decision IN ('approve','reject','needs_more_data')",
            name="ck_cq_candidates_review_decision",
        ),
        Index("idx_cq_candidates_status", "status"),
    )


class SavedQuery(Base):
    """The `saved_queries` table: the personalization investment loop's storage (Section 15)."""

    __tablename__ = "saved_queries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    query_text: Mapped[str] = mapped_column(Text, nullable=False)
    label: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_run_interaction_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("interactions.id", ondelete="SET NULL"), nullable=True
    )


class GuestSession(Base):
    """The `guest_sessions` table: an anonymous visitor's counted allowance.

    Build phase 4.10, T-4.10-02, design decision 3
    (`tracker/phase_4.10.md`): one row per guest identity, holding the
    server-side count `data.guest_sessions.spend_one_run` advances with a
    single conditional `UPDATE ... RETURNING`, never a `SELECT` followed
    by an `UPDATE`. Distinct from `AuthSession` above, which tracks a
    registered login's refresh-token state: this tracks a caller with no
    `users` row at all.

    `migrated_to_user_id` is set, and `revoked_at` is set in the same
    transaction, when a guest signs up or logs in while holding a live
    guest token (design decision 4): the guest's runs move to the new
    account and the guest token can no longer spend. `ON DELETE SET NULL`
    so deleting a user row never fails or cascades onto this table.
    """

    __tablename__ = "guest_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    runs_used: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    # F-4.10-R-01, product-owner decision 2026-08-15. The SECOND counter on
    # this row, and the two are not redundant. `runs_used` counts ANSWERS and
    # is refunded when the guardrail refuses, so a curious visitor is not
    # punished for one clumsy question. `attempts_used` counts every run this
    # identity STARTS and is never refunded, so the refund cannot leave the
    # identity unbounded.
    #
    # Why that matters, measured rather than reasoned about: with only
    # `runs_used`, one guest token minted once started 200 paid pipelines in
    # 1.68 seconds while its own allowance still read `used: 0`, draining the
    # whole day's anonymous budget for every other visitor. A refusal cost the
    # caller nothing and cost everyone else a slot. This column is the
    # per-identity bound the refund removed.
    attempts_used: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    migrated_to_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    __table_args__ = (
        CheckConstraint("runs_used >= 0", name="ck_guest_sessions_runs_used"),
        CheckConstraint("attempts_used >= 0", name="ck_guest_sessions_attempts_used"),
    )


class GuestDailyUsage(Base):
    """The `guest_daily_usage` table: one row per UTC day, counting every
    anonymous run the whole system has started that day.

    Build phase 4.10, design decision 8 (`tracker/phase_4.10.md`), added
    after the adversary round measured 40 paid pipelines accepted in 0.25
    seconds from a caller with no account (F-4.10-A-01).

    Why this table exists when `guest_sessions.runs_used` already counts:
    that counter is keyed on a guest identity, and `POST /auth/guest` mints
    identities for free, so it bounds a variable the caller controls the
    supply of. This one is keyed on the calendar day, which nobody controls
    the supply of, and it is therefore the only real ceiling on what an
    anonymous caller can spend. The per-IP mint throttle in
    `auth/router.py` sits in front of it as defense in depth, and is
    explicitly not the bound, since a rotating source defeats it.

    `day` is the primary key and is a DATE in UTC, never the server's local
    date: a cap that resets at an operator's midnight rather than a fixed
    one is a cap whose window silently moves with a deployment's timezone.
    """

    __tablename__ = "guest_daily_usage"

    day: Mapped[date] = mapped_column(Date, primary_key=True)
    runs_used: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("0"))

    __table_args__ = (
        CheckConstraint("runs_used >= 0", name="ck_guest_daily_usage_runs_used"),
    )
