"""SQLAlchemy ORM models for the user-data schema.

Spec: Technical_specification.md Section 15 (lines 2361-2555), the six
tables `users`, `auth_sessions`, `sessions`, `interactions`, `cq_candidates`,
`saved_queries`.

Depends on:
    - system_03_search_agent.data.base (Base)

Reads:
    - Nothing at import time.

Writes:
    - Nothing at import time. Table creation is owned exclusively by the
      Alembic migration in alembic/versions/0001_user_data_schema.py, never
      by Base.metadata.create_all() in application code.

This module never imports, references, or constructs a connection to the
knowledge-graph database or its read-only role.

The `alembic/versions/0001_user_data_schema.py` migration is hand-written
directly from Section 15's SQL rather than autogenerated from these classes,
so it is the authoritative source for exact index definitions (index name,
column order direction, and opclass). The Index objects declared here mirror
the migration for ORM-level documentation and future autogenerate diffing;
where a plain SQLAlchemy Index cannot express a Postgres-specific detail
(the `created_at DESC` ordering), the ORM declaration is a same-column,
ascending best-effort mirror and the migration remains authoritative.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    ARRAY,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    SmallInteger,
    Text,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from system_03_search_agent.data.base import Base


class User(Base):
    """The `users` table: one row per registered account (Section 15)."""

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    email: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    profile: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    __table_args__ = (
        # F-1.1-08: the plain UNIQUE on `email` above is byte-exact, so
        # `USER@example.com` and `user@example.com` are two accounts. The
        # case-insensitive guarantee is this functional unique index on
        # `lower(email)`, added in alembic revision 0002, which holds even
        # for a code path that skips the schema-level normalization in
        # auth/schemas.py.
        Index("ux_users_email_lower", text("lower(email)"), unique=True),
    )


class AuthSession(Base):
    """The `auth_sessions` table: login state and refresh tokens (Section 15).

    Distinct from `ChatSession` below: this tracks login state, the chat
    session tracks a query workspace. Revoking a login must never erase a
    running conversation's context.
    """

    __tablename__ = "auth_sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    refresh_token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    # F-1.1-07: the ceiling a whole rotation chain may never outlive,
    # carried forward unchanged from the login that started the chain,
    # unlike `expires_at`, which every rotation renews. Nullable because
    # revision 0002 adds it to a table that already holds rows; a NULL
    # means a row written before that revision, and the router treats it
    # as capped at `created_at + the absolute TTL`.
    absolute_expires_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    user_agent: Mapped[str | None] = mapped_column(Text, nullable=True)
    ip_hash: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        # F-1.1-12: every auth call filters this column, and nothing
        # prevented two rows from sharing a hash. A unique index is both
        # halves of that finding at once, the uniqueness the code already
        # assumed and the index the lookups always needed.
        Index("ux_auth_sessions_refresh_token_hash", "refresh_token_hash", unique=True),
    )


class ChatSession(Base):
    """The `sessions` table: a chat or query workspace session (Section 15).

    Named ChatSession at the Python class level (the table name stays
    `sessions`) so this never collides with sqlalchemy.orm.Session.
    """

    __tablename__ = "sessions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_active_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    experiment_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    experiment_arm: Mapped[str | None] = mapped_column(Text, nullable=True)


class Interaction(Base):
    """The `interactions` table: the feedback-loop and memory substrate (Section 15)."""

    __tablename__ = "interactions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    trace_id: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    session_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("sessions.id", ondelete="SET NULL"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    query_text: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_entities: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    query_class: Mapped[str] = mapped_column(Text, nullable=False)
    route: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)

    trust_signal: Mapped[str] = mapped_column(Text, nullable=False)
    rubric_outcome: Mapped[str] = mapped_column(Text, nullable=False)
    rubric_score: Mapped[int | None] = mapped_column(SmallInteger, nullable=True)

    citations: Mapped[list[Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    coverage_tags: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default=text("'{}'::text[]")
    )
    user_feedback: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    experiment_id: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    experiment_arm: Mapped[str | None] = mapped_column(Text, nullable=True)
    cost_usd: Mapped[Any | None] = mapped_column(Numeric(9, 6), nullable=True)
    latency_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    __table_args__ = (
        CheckConstraint(
            "query_class IN ('lookup','single_hop','multi_hop','aggregate','exploratory')",
            name="ck_interactions_query_class",
        ),
        CheckConstraint(
            "trust_signal IN ('answer','flag','ask','refuse')",
            name="ck_interactions_trust_signal",
        ),
        CheckConstraint(
            "rubric_outcome IN ('pass','fail','abstain')",
            name="ck_interactions_rubric_outcome",
        ),
        CheckConstraint(
            "rubric_score BETWEEN 0 AND 16",
            name="ck_interactions_rubric_score",
        ),
        Index("idx_interactions_created_at", "created_at"),
        Index("idx_interactions_user_id", "user_id"),
        Index("idx_interactions_rubric", "rubric_outcome"),
        Index("idx_interactions_coverage_tags", "coverage_tags", postgresql_using="gin"),
        Index(
            "idx_interactions_query_trgm",
            "query_text",
            postgresql_using="gin",
            postgresql_ops={"query_text": "gin_trgm_ops"},
        ),
    )


class CqCandidate(Base):
    """The `cq_candidates` table: proposed and promoted competency questions (Section 15)."""

    __tablename__ = "cq_candidates"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )

    status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'proposed'")
    )
    representative_query: Mapped[str] = mapped_column(Text, nullable=False)
    source_interaction_ids: Mapped[list[uuid.UUID]] = mapped_column(
        ARRAY(UUID(as_uuid=True)), nullable=False, server_default=text("'{}'::uuid[]")
    )
    frequency_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default=text("1"))

    wedge_type: Mapped[str | None] = mapped_column(Text, nullable=True)
    moat_gate_provenance: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    moat_gate_deterministic: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    moat_rank: Mapped[str | None] = mapped_column(Text, nullable=True)
    llm_judge_rationale: Mapped[str | None] = mapped_column(Text, nullable=True)

    reviewed_by: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    review_decision: Mapped[str | None] = mapped_column(Text, nullable=True)
    review_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    few_shot_example: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    eval_case: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    promoted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    __table_args__ = (
        CheckConstraint(
            "status IN ('proposed','approved','rejected','promoted','retired')",
            name="ck_cq_candidates_status",
        ),
        CheckConstraint(
            "wedge_type IN ('gene-variant-literature','pathogen-sequence-outbreak',"
            "'paper-data-tool','other')",
            name="ck_cq_candidates_wedge_type",
        ),
        CheckConstraint(
            "moat_rank IN ('tier_1','tier_2','none')",
            name="ck_cq_candidates_moat_rank",
        ),
        CheckConstraint(
            "review_decision IN ('approve','reject','needs_more_data')",
            name="ck_cq_candidates_review_decision",
        ),
        Index("idx_cq_candidates_status", "status"),
    )


class SavedQuery(Base):
    """The `saved_queries` table: the personalization investment loop's storage (Section 15)."""

    __tablename__ = "saved_queries"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    query_text: Mapped[str] = mapped_column(Text, nullable=False)
    label: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    last_run_interaction_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("interactions.id", ondelete="SET NULL"), nullable=True
    )
