"""User-data schema: users, auth_sessions, sessions, interactions, cq_candidates, saved_queries.

Revision ID: 0001_user_data_schema
Revises:
Create Date: 2026-07-28

Spec: requirements/Technical_specification.md Section 15 (lines 2361-2555).
Hand-written directly from the spec's SQL, not autogenerated, so this file
is the single authoritative source for exact table shape, CHECK
constraints, indexes (including opclass and sort order), and extensions.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0001_user_data_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Extensions the user-data instance depends on: pgcrypto for
    # gen_random_uuid() primary keys, pg_trgm for the trigram index the
    # feedback loop (Section 16) will use.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "users",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("email", sa.Text(), nullable=False, unique=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "profile",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )

    op.create_table(
        "auth_sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("refresh_token_hash", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_hash", sa.Text(), nullable=True),
    )

    op.create_table(
        "sessions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_active_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("experiment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("experiment_arm", sa.Text(), nullable=True),
    )

    op.create_table(
        "interactions",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("trace_id", sa.Text(), nullable=False, unique=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column(
            "normalized_entities",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("query_class", sa.Text(), nullable=False),
        sa.Column("route", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trust_signal", sa.Text(), nullable=False),
        sa.Column("rubric_outcome", sa.Text(), nullable=False),
        sa.Column("rubric_score", sa.SmallInteger(), nullable=True),
        sa.Column(
            "citations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "coverage_tags",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column("user_feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("experiment_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("experiment_arm", sa.Text(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(9, 6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "query_class IN ('lookup','single_hop','multi_hop','aggregate','exploratory')",
            name="ck_interactions_query_class",
        ),
        sa.CheckConstraint(
            "trust_signal IN ('answer','flag','ask','refuse')",
            name="ck_interactions_trust_signal",
        ),
        sa.CheckConstraint(
            "rubric_outcome IN ('pass','fail','abstain')",
            name="ck_interactions_rubric_outcome",
        ),
        sa.CheckConstraint(
            "rubric_score BETWEEN 0 AND 16",
            name="ck_interactions_rubric_score",
        ),
    )

    # Exact per Section 15: created_at DESC and the trigram opclass are not
    # expressible via op.create_index() alone, so these two are raw DDL.
    op.execute("CREATE INDEX idx_interactions_created_at ON interactions (created_at DESC)")
    op.create_index("idx_interactions_user_id", "interactions", ["user_id"])
    op.create_index("idx_interactions_rubric", "interactions", ["rubric_outcome"])
    op.execute(
        "CREATE INDEX idx_interactions_coverage_tags ON interactions USING GIN (coverage_tags)"
    )
    op.execute(
        "CREATE INDEX idx_interactions_query_trgm "
        "ON interactions USING GIN (query_text gin_trgm_ops)"
    )

    op.create_table(
        "cq_candidates",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'proposed'")),
        sa.Column("representative_query", sa.Text(), nullable=False),
        sa.Column(
            "source_interaction_ids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
            server_default=sa.text("'{}'::uuid[]"),
        ),
        sa.Column("frequency_count", sa.Integer(), nullable=False, server_default=sa.text("1")),
        sa.Column("wedge_type", sa.Text(), nullable=True),
        sa.Column("moat_gate_provenance", sa.Boolean(), nullable=True),
        sa.Column("moat_gate_deterministic", sa.Boolean(), nullable=True),
        sa.Column("moat_rank", sa.Text(), nullable=True),
        sa.Column("llm_judge_rationale", sa.Text(), nullable=True),
        sa.Column("reviewed_by", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_decision", sa.Text(), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("few_shot_example", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("eval_case", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('proposed','approved','rejected','promoted','retired')",
            name="ck_cq_candidates_status",
        ),
        sa.CheckConstraint(
            "wedge_type IN ('gene-variant-literature','pathogen-sequence-outbreak',"
            "'paper-data-tool','other')",
            name="ck_cq_candidates_wedge_type",
        ),
        sa.CheckConstraint(
            "moat_rank IN ('tier_1','tier_2','none')",
            name="ck_cq_candidates_moat_rank",
        ),
        sa.CheckConstraint(
            "review_decision IN ('approve','reject','needs_more_data')",
            name="ck_cq_candidates_review_decision",
        ),
    )
    op.create_index("idx_cq_candidates_status", "cq_candidates", ["status"])

    op.create_table(
        "saved_queries",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_run_interaction_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("interactions.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )


def downgrade() -> None:
    # Reverse FK dependency order so no drop fails on a live reference.
    op.drop_table("saved_queries")
    op.drop_table("cq_candidates")
    op.drop_table("interactions")
    op.drop_table("sessions")
    op.drop_table("auth_sessions")
    op.drop_table("users")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    op.execute("DROP EXTENSION IF EXISTS pgcrypto")
