import json
import sys

Q = [
    "SRA runs from COVID-19 patients",
    "Find SRA runs of COVID-19 nasal swabs",
    "HIV-1 genome assemblies",
    "SRA runs of HIV-1 infected T cells",
    "SRA runs from HIV-positive patients",
    "SRA runs from AML-derived cell lines",
    "SRA runs of ALS-associated motor neurons",
    "SRA runs of TNBC-derived organoids",
    "SRA runs of COPD-related lung samples",
    "SRA runs of BRCA1-mutant breast tumours",
    "SRA runs of TP53-null cells",
    "SRA runs of KRAS-G12D tumours",
    "Hepatitis-B virus genome assemblies",
    "type-1 diabetes SRA runs",
    "SARS and SARS-CoV-2 SRA runs",
    "SRA runs of SARS CoV 2",
    "SRA runs of SARS CoV-2",
    "SRA runs of SARS­CoV­2",
    "SRA runs of SARS/CoV-2",
    "SRA runs of SARS.CoV.2",
    "SRA runs of (SARS)-CoV-2",
    "SRA runs of SARS—CoV—2",
    "SRA runs of SARS−CoV−2",
    "SRA runs of SARS -CoV-2",
    "SRA runs of SARS -CoV-2",
    "SRA runs of SARS- CoV-2",
    "SRA runs of SARS‐CoV‐2 and MERS",
    "SRA runs of SARS‑CoV‑2",
    "SRA runs of SARS－CoV－2",
    "SRA runs of SARS⁃CoV⁃2",
    "SRA runs of SARS˗CoV˗2",
    "SRA runs of SARS⸺CoV-2",
    "SRA runs of MERS-CoV",
    "SRA runs of MODY-like patients and MODY families",
    "SRA runs of H5N1-infected ducks",
    "SRA runs - MODY patients",
    "SARS-CoV-2 sequencing papers",
    "Latest SARS-CoV-2 research",
    "SRA runs of IBD-associated E. coli",
    "SRA runs of CF-patient Pseudomonas isolates",
    "SRA runs of CML-BCR-ABL cells",
    "SRA runs of ALS",
    "Find SRA runs from ALS-patients",
]
print(
    json.dumps(
        [{"q": q, "ents": [], "rt": rt} for q in Q for rt in sys.argv[1].split(",")],
        ensure_ascii=True,
    )
)
